### ISSUE TITLE
Filenames not quoted in bash

### ISSUE THREAD

**Issue by kofalt** [scitran/apps#12]
Discovered by @ryansanford - the use of basename [here](https://github.com/scitran/apps/blob/b59bbb775644b9d7566c6b17533c8e05ab8c8f7f/classifier/dicom-mr-classifier/run#L29) does not quote the file name, and thus will not work with filenames that have spaces.

```
basename: extra operand 'SSFSE.zip'
Try 'basename --help' for more information.
usage: dicom-mr-classifier.py [-h] [--log_level LOG_LEVEL] dcmtgz [outbase]
dicom-mr-classifier.py: error: unrecognized arguments: SSFSE.zip /flywheel/v0/output/
No results found in output directory... Exiting
Exit was 1
```

It may be that other parts of the same script, and / or the other wrappers, also need quotes added.

**Comment by lmperry** [comment]
This same issues exists in dcm-convert and qa-report-fmri. A fix is in testing now.

**Comment by lmperry** [comment]
@ryansanford: please note the update for dcm-convert and qa-report-fmri gears.

**Comment by ryansanford** [comment]
Thanks, will re-build gears shortly.


On Mon, Apr 4, 2016 at 4:44 PM, Michael Perry <notifications@github.com>
wrote:

> @ryansanford <https://github.com/ryansanford>: please note the update for
> dcm-convert and qa-report-fmri gears.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scitran/apps/issues/12#issuecomment-205510847>
>



-- 

*Ryan Sanford* | *Dev Ops Engineer*





O: 612.223.7359 X2167

ryansanford@flywheel.io

www.flywheel.io
