### ISSUE TITLE
Add timezone info to classifier gear timestamps

### ISSUE THREAD

**Issue by nagem** [scitran/apps#15]
scitran/core expects [rfc3339](https://tools.ietf.org/html/rfc3339) format for session/acquisition timestamps via the `date-time` format option in the json schema files. The gear is failing to upload results properly as the metadata for the session and acquisition sent to the `api/engine` endpoint contains timestamps without a timezone specified. Either an offset or `Z` for UTC must be appended for the metadata to be valid.

**Comment by ryansanford** [comment]
@lmperry do you have cycles to look at this today? This is a blocker to distributing the latest scitran/core at commit 16d33124f8f13db9dcb6c024e0752f67580d21d3 or newer to any sites.
