### ISSUE TITLE
Directory input not implemented

### ISSUE THREAD

**Issue by kofalt** [scitran/apps#2]
Playing with dicom conversion; what am I doing wrong?

```
# /script/dcm2nii /input/ /output
locating input...
loading input...
No handlers could be found for logger "scitran.data.data"
Traceback (most recent call last):
  File "/script/dcm2nii", line 38, in <module>
    dcm2nii(args.input, args.outbase)
  File "/script/dcm2nii", line 17, in dcm2nii
    ds = scidata.parse(inpath, filetype='dicom', load_data=True, ignore_json=True)
  File "/usr/local/lib/python2.7/dist-packages/scitran/data/data.py", line 391, in parse
    raise DataError('directory input not implemented', log_level=logging.ERROR)
scitran.data.data.DataError: directory input not implemented
```

Where `/input` is the result of untaring a random demo.flywheel.io instance, holding a folder `4374_2_1_dicoms/` which in turn holds 166 `.dcm` files.

This is running in a `scitran/nipa-base` image built this afternoon, with the contents of this repo's `dcm2nii` folder mounted in as `/script`.

**Comment by kevlarkevin** [comment]
No need to untar.  `dcm2nii` is expecting a tgz.

**Comment by kofalt** [comment]
Ah, fair enough. Do you read directly from the tarstream? 
My framework is currently assuming tarballs as inputs, and helpfully untars them where asked.

If this script will literally always use a tarball as an input in every scenario for the rest of time (remote S3 mounting, etc), then I should change my input to just move a file around (or download it) without untaring. There may be clear advantages to being able to do stream processing, basically.

**Comment by kevlarkevin** [comment]
Not truly reading from the tarstream.  We extract the files into memory, so those file like objects can be read by a dicom library.  The tarball doesn't get unpacked into the filesystem.

Currently, the plan is for `dcm2nii` to always use a tarball as an input in every scenario for the rest of time. If this were to change it would most likely be reading from a zip file instead of a tarfile.

**Comment by kofalt** [comment]
Sounds good! That works for me, then.

**Comment by kofalt** [comment]
.
