### ISSUE TITLE
Latest dcm-convert gear is failing with python Import error

### ISSUE THREAD

**Issue by ryansanford** [scitran/apps#22]
Error from flywheel engine

```
engine_1          | Traceback (most recent call last):
engine_1          |   File "/flywheel/v0/dcm-convert.py", line 9, in <module>
engine_1          |     import scitran.data as scidata
engine_1          | ImportError: No module named scitran.data
```

Gear being used
https://storage.googleapis.com/flywheel/gears/v1/scitran/dcm-convert/dcm-convert_latest_20161026T174418.079227Z.json

**Comment by lmperry** [comment]
Spent a while looking into this. The latest gear works locally (no engine) when run through the testing data. Finally installed the latest version of the gear (see snippet below) on the instance at Stanford (cayman 4.1) and manually ran a couple of datasets using that gear and can't replicate what you're seeing there. 

Here's the snippet of the `gear-config.json` for the instance here. 
```
    {
      "gear_doc_url" : "https://storage.googleapis.com/flywheel/gears/v1/scitran/dcm-convert/dcm-convert_latest_20161026T174418.079227Z.json",
      "gear_category" : "converter"
    },
```
