### ISSUE TITLE
Directory output

### ISSUE THREAD

**Issue by kofalt** [scitran/apps#3]
Entirely orthogonal to #2, it would be nice to ask dcm2nii to just place all its output in a folder. 

My framework gig is comfortable with wrapping up an output folder in some way; may as well let me handle it :)

**Comment by kevlarkevin** [comment]
Can you clarify?  I'm not sure what you're asking for.

Do you want the `dcm2nii` script inside the container, to output somewhere different than `/output`?  Or do you want to be able to specify that the container itself place all it's outputs in a host folder? Or do you want all outputs to show up in a subdirectory of the mounted host folder?

**Comment by kofalt** [comment]
Haha, yes, I see now that I was terribly unclear.

What I was *trying* (and failing) to ask for was, can I get `dcm2nii` to *not* tarball its results?

I might want to reason about the output, and have already planned to tar up generic algorithm results. Right now with my prototype, I thus end up with a tar of a tar :P

**Comment by kevlarkevin** [comment]
`dcm2nii` already does *not* tarball its results.  It should output **.nii.gz** file.

**Comment by kofalt** [comment]
Ah, I misunderstood. Assumed that was a tarball. Not A Smart Man.
